"""empty message

Revision ID: 51df088ca35f
Revises: 
Create Date: 2023-02-10 22:04:32.549691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51df088ca35f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caja_anual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Date(), nullable=True),
    sa.Column('totalmensualidades', sa.Integer(), nullable=False),
    sa.Column('cantidadalumnos', sa.Integer(), nullable=True),
    sa.Column('totalventas', sa.Integer(), nullable=True),
    sa.Column('totalpagoprov', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caja_diaria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('totalmensualidades', sa.Integer(), nullable=False),
    sa.Column('cantidadalumnos', sa.Integer(), nullable=True),
    sa.Column('totalventas', sa.Integer(), nullable=True),
    sa.Column('totalpagoprov', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caja_mensual',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('totalmensualidades', sa.Integer(), nullable=False),
    sa.Column('cantidadalumnos', sa.Integer(), nullable=True),
    sa.Column('totalventas', sa.Integer(), nullable=True),
    sa.Column('totalpagoprov', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('precio', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metodospago',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutualista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=True),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('mail', sa.String(length=120), nullable=True),
    sa.Column('observaciones', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('tipoejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ejercicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('foto', sa.String(length=250), nullable=True),
    sa.Column('video', sa.String(length=250), nullable=True),
    sa.Column('idtipo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idtipo'], ['tipoejercicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagoproveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechapago', sa.Date(), nullable=True),
    sa.Column('numfactura', sa.Integer(), nullable=True),
    sa.Column('monto', sa.String(length=10), nullable=True),
    sa.Column('observaciones', sa.String(length=120), nullable=True),
    sa.Column('idproveedor', sa.Integer(), nullable=True),
    sa.Column('idmetodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idmetodo'], ['metodospago.id'], ),
    sa.ForeignKeyConstraint(['idproveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precioventa', sa.String(length=10), nullable=False),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('video', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('proveedorid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proveedorid'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('apellido', sa.String(length=50), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('fechanacimiento', sa.String(length=15), nullable=True),
    sa.Column('condicionesmedicas', sa.String(length=200), nullable=True),
    sa.Column('medicacion', sa.String(length=200), nullable=True),
    sa.Column('emergencias', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('rol', sa.String(length=15), nullable=True),
    sa.Column('motivoentrenamiento', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('foto', sa.String(length=500), nullable=True),
    sa.Column('celular', sa.String(length=15), nullable=True),
    sa.Column('peso', sa.String(length=10), nullable=True),
    sa.Column('altura', sa.String(length=10), nullable=True),
    sa.Column('fechaingreso', sa.String(length=15), nullable=True),
    sa.Column('activo', sa.String(length=10), nullable=False),
    sa.Column('idcuota', sa.Integer(), nullable=True),
    sa.Column('idmutualista', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcuota'], ['cuota.id'], ),
    sa.ForeignKeyConstraint(['idmutualista'], ['mutualista.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('carrito',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idcarrito', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('idproductos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idproductos'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preciocompra', sa.String(length=10), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('idproducto', sa.Integer(), nullable=True),
    sa.Column('idproveedor', sa.Integer(), nullable=True),
    sa.Column('idmetodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idmetodo'], ['metodospago.id'], ),
    sa.ForeignKeyConstraint(['idproducto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['idproveedor'], ['proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensualidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechapago', sa.String(length=10), nullable=True),
    sa.Column('monto', sa.String(length=10), nullable=True),
    sa.Column('factura', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('idmetodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idmetodo'], ['metodospago.id'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechacomienzo', sa.Date(), nullable=True),
    sa.Column('fechafinalizacion', sa.Date(), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechacompra', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('preciounitario', sa.String(length=10), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('fechapago', sa.Date(), nullable=True),
    sa.Column('idproducto', sa.Integer(), nullable=True),
    sa.Column('idmetodo', sa.Integer(), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idmetodo'], ['metodospago.id'], ),
    sa.ForeignKeyConstraint(['idproducto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rutinas_aux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.Integer(), nullable=True),
    sa.Column('carga', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('idrutina', sa.Integer(), nullable=True),
    sa.Column('idejercicio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idejercicio'], ['ejercicio.id'], ),
    sa.ForeignKeyConstraint(['idrutina'], ['rutina.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventasonline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fechapago', sa.Date(), nullable=True),
    sa.Column('ordernumber', sa.String(length=25), nullable=True),
    sa.Column('observaciones', sa.String(length=150), nullable=True),
    sa.Column('idusuario', sa.Integer(), nullable=True),
    sa.Column('idcarrito', sa.Integer(), nullable=True),
    sa.Column('idmetodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idcarrito'], ['carrito.id'], ),
    sa.ForeignKeyConstraint(['idmetodo'], ['metodospago.id'], ),
    sa.ForeignKeyConstraint(['idusuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventasonline')
    op.drop_table('rutinas_aux')
    op.drop_table('ventas')
    op.drop_table('rutina')
    op.drop_table('mensualidades')
    op.drop_table('compras')
    op.drop_table('carrito')
    op.drop_table('usuarios')
    op.drop_table('productos')
    op.drop_table('pagoproveedores')
    op.drop_table('ejercicio')
    op.drop_table('user')
    op.drop_table('tipoejercicio')
    op.drop_table('proveedores')
    op.drop_table('mutualista')
    op.drop_table('metodospago')
    op.drop_table('cuota')
    op.drop_table('caja_mensual')
    op.drop_table('caja_diaria')
    op.drop_table('caja_anual')
    # ### end Alembic commands ###
