"""empty message

Revision ID: c87605323643
Revises: 2add047c7b8b
Create Date: 2023-02-06 16:55:34.135254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87605323643'
down_revision = '2add047c7b8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fechanacimiento',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('fechaingreso',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('fechaingreso',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('fechanacimiento',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
